package com.infy.utility;

public interface CategoryConstants {
	int DASHBOARD =1;
	int MUTIPLE_TRIGGERS= 2;
	int INACTIVE_VALIDATIONRULE=3;
	int JOBS_GENERIC_ID =4;
	int SYSTEM_RUNAS = 5;
	int TRIGGER_NAMING_CONVENTION=6;
	int SYSTEM_DEBUG_CNT=7;
	int SQLDML_EXCEPTION_HANDLING= 8;
	int METHOD_TOOLARGE=9;
	int SOQL_IN_BATCH_CLS = 10;
	int SQLDML_EXCEHANDLING_TRG= 11;
	int RECORDTYE_INFO=12;
	int SOQL_LIMIT=13;
	int SQL_DML_SARTSTOP_TEST=14;
//	int SYSTEM_ASSERT =14;
	int INAPPR_COMMENTLOC=15;
	int DOCTYPE=16;
	int INACTIVE_USER=17;
	int INLINE_JAVASCRIPT=18;
	int INLINE_CSS=19;
	int INACTIVE_TGR=20;
	int INACTIVE_WORKFLOWRULE=21;
	int  MULTIPLE_FIELD_UPDATE= 22;
	
	//APEX PMD RULES	
	int  SEEALL_DATA_TRUE = 100;
	int  APEX_ASSERTS = 101;
	int  AVOID_GLOBAL_MODIFIER=102;	
	int  LOGIC_IN_TRIGGER = 103;
	int  CLASS_NAMING_CONVENTION = 104;
	int  METHOD_NAMING_CONVENTION= 105;
	int  VARIABLE_NAMING_CONVENTION= 106;
	int  HARD_CODED_ID_FOUND= 107;
	int  AVOID_DML_STATEMENTS_IN_LOOPS= 108;
	int  AVOID_SOQL_STATEMENTS_IN_LOOPS= 109;
	int  AVOID_SOSL_STATEMENTS_IN_LOOPS= 110;
	int  CYLCOMATIC_COMPLEXITY = 111;
	int  APEX_BAD_CRYPTO= 112;
	int  APEX_CRUD_VIOLATION= 113;
	int  APEXCSRF= 114;
	int  APEX_DANGEROUS_METHODS= 115;
	int  APEX_INSECURE_ENDPOINT= 116;
	int  APEX_OPEN_REDIRECT= 117;
	int  APEX_SHARING_VIOLATIONS= 118;
	int  APEX_SOQL_INJECTION= 119;
	int  APEX_SUGGEST_USING_NAMED_CRED= 120;
	int  APEX_XSS_FROM_ESCAPE_FALSE= 121;
	int  APEXXSSFROMURLPARAM= 122;
	int  METHODAME_MATCHES_ENCLOSING_CLSNAME= 123;
	
	
	
	
	
}
